"""Add user session tracking

Revision ID: 45539a479aad
Revises: 9dd08039f239
Create Date: 2026-09-13 12:40:24.343742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45539a479aad'
down_revision: Union[str, Sequence[str], None] = '9dd08039f239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adminId', sa.String(length=50), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adminId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('profile_name', sa.String(length=50), nullable=False),
    sa.Column('profile_pic', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'profile_name', name='uq_user_profile_name')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_userId'), 'user_profiles', ['userId'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.String(length=50), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_profile_id'), 'user_sessions', ['profile_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_userId'), 'user_sessions', ['userId'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('profile_flag', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('updated_time', sa.DateTime(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_time')
    op.drop_column('users', 'profile_flag')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_user_sessions_userId'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_profile_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_profiles_userId'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('admin_sessions')
    # ### end Alembic commands ###
