"""Add user session tokkens

Revision ID: 6072076e7c79
Revises: 45539a479aad
Create Date: 2026-09-13 13:38:51.485934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6072076e7c79'
down_revision: Union[str, Sequence[str], None] = '45539a479aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_sessions', sa.Column('session_token', sa.String(length=36), nullable=False))
    op.add_column('user_sessions', sa.Column('session_token', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'session_token')
    op.drop_column('admin_sessions', 'session_token')
    # ### end Alembic commands ###
